version: '3.6'

services:
  api:
    build: https://github.com/n-misharin/Mega-Market-Open-API.git#master
    depends_on:
      - db
    environment:
      APP_SETTINGS: config.Config
      DATABASE_URL: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 80:80
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data